models:
  - type: main
    engine: azure
    model: ${AZURE_OPENAI_DEPLOYMENT_NAME}

rails:
  config:
    moderation:
      input: []
       #   - type: llama_guard
       #     model: meta-llama/Meta-LlamaGuard-3-8B